name: CI pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Code checkout
          uses: actions/checkout@v6
            
        - name: Deploy page to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./
